BEGIN;

CREATE TABLE IF NOT EXISTS skills (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    skill_idx        INTEGER,
    skill_name       TEXT NOT NULL,
    skill_level      INTEGER,
    skill_2d_image   INTEGER,
    skill_tooltip    INTEGER,
    operator_effect  INTEGER,
    target_effect    INTEGER,
    skill_effect     INTEGER,
    animation_time   INTEGER,
    casting_time     INTEGER,
    cool_time        INTEGER,
    delay_time       INTEGER,
    delay_type       INTEGER,
    is_battle        INTEGER,
    is_peace         INTEGER,
    is_move          INTEGER,
    is_stop          INTEGER,
    empty_1          INTEGER,
    require_buff     INTEGER,
    target           INTEGER,
    kind             INTEGER,
    empty_2          INTEGER,
    equip            INTEGER,
    empty_3          INTEGER,
    empty_4          INTEGER,
    area             INTEGER,
    area_target      INTEGER,
    area_data        INTEGER,
    unit             INTEGER,
    unit_data_type   TEXT,
    success          INTEGER,
    empty_5          INTEGER,
    cancel           INTEGER,
    range            INTEGER,
    consume_type     INTEGER,
    consume_value    INTEGER,
    consume_item_qty INTEGER,
    money            INTEGER,
    mana             TEXT,
    life             INTEGER,
    train_point      INTEGER,
    train_money      INTEGER,
    buff_id_1        INTEGER,
    rate_buff_1      INTEGER,
    buff_id_2        INTEGER,
    rate_buff_2      INTEGER,
    buff_id_3        INTEGER,
    rate_buff_3      INTEGER,
    buff_id_4        INTEGER,
    rate_buff_4      INTEGER,
    buff_id_5        INTEGER,
    rate_buff_5      INTEGER,
    is_move_2        INTEGER,
    req_player_level INTEGER
);

-- 2. Clear existing data
TRUNCATE TABLE skills RESTART IDENTITY;

-- 3. Import fresh data
COPY skills (
    skill_idx,
    replace(skill_name,'^s', ' '),
    skill_level,
    skill_2d_image,
    skill_tooltip,
    operator_effect,
    target_effect,
    skill_effect,
    animation_time,
    casting_time,
    cool_time,
    delay_time,
    delay_type,
    is_battle,
    is_peace,
    is_move,
    is_stop,
    empty_1,
    require_buff,
    target,
    kind,
    empty_2,
    equip,
    empty_3,
    empty_4,
    area,
    area_target,
    area_data,
    unit,
    unit_data_type,
    success,
    empty_5,
    cancel,
    range,
    consume_type,
    consume_value,
    consume_item_qty,
    money,
    mana,
    life,
    train_point,
    train_money,
    buff_id_1,
    rate_buff_1,
    buff_id_2,
    rate_buff_2,
    buff_id_3,
    rate_buff_3,
    buff_id_4,
    rate_buff_4,
    buff_id_5,
    rate_buff_5,
    is_move_2,
    req_player_level
)
FROM '/script/CSV/skillList.csv'
DELIMITER ','
CSV;

COMMIT;